# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/Data/Unscrambler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/Data/Unscrambler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/Data/Unscrambler/CMakeFiles /mnt/Data/Unscrambler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/Data/Unscrambler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Unscrambler

# Build rule for target.
Unscrambler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Unscrambler
.PHONY : Unscrambler

# fast build rule for target.
Unscrambler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Unscrambler.dir/build.make CMakeFiles/Unscrambler.dir/build
.PHONY : Unscrambler/fast

Combinations.o: Combinations.cpp.o
.PHONY : Combinations.o

# target to build an object file
Combinations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Unscrambler.dir/build.make CMakeFiles/Unscrambler.dir/Combinations.cpp.o
.PHONY : Combinations.cpp.o

Combinations.i: Combinations.cpp.i
.PHONY : Combinations.i

# target to preprocess a source file
Combinations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Unscrambler.dir/build.make CMakeFiles/Unscrambler.dir/Combinations.cpp.i
.PHONY : Combinations.cpp.i

Combinations.s: Combinations.cpp.s
.PHONY : Combinations.s

# target to generate assembly for a file
Combinations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Unscrambler.dir/build.make CMakeFiles/Unscrambler.dir/Combinations.cpp.s
.PHONY : Combinations.cpp.s

Main.o: Main.cpp.o
.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Unscrambler.dir/build.make CMakeFiles/Unscrambler.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i
.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Unscrambler.dir/build.make CMakeFiles/Unscrambler.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s
.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Unscrambler.dir/build.make CMakeFiles/Unscrambler.dir/Main.cpp.s
.PHONY : Main.cpp.s

Runner.o: Runner.cpp.o
.PHONY : Runner.o

# target to build an object file
Runner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Unscrambler.dir/build.make CMakeFiles/Unscrambler.dir/Runner.cpp.o
.PHONY : Runner.cpp.o

Runner.i: Runner.cpp.i
.PHONY : Runner.i

# target to preprocess a source file
Runner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Unscrambler.dir/build.make CMakeFiles/Unscrambler.dir/Runner.cpp.i
.PHONY : Runner.cpp.i

Runner.s: Runner.cpp.s
.PHONY : Runner.s

# target to generate assembly for a file
Runner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Unscrambler.dir/build.make CMakeFiles/Unscrambler.dir/Runner.cpp.s
.PHONY : Runner.cpp.s

SpellChecker.o: SpellChecker.cpp.o
.PHONY : SpellChecker.o

# target to build an object file
SpellChecker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Unscrambler.dir/build.make CMakeFiles/Unscrambler.dir/SpellChecker.cpp.o
.PHONY : SpellChecker.cpp.o

SpellChecker.i: SpellChecker.cpp.i
.PHONY : SpellChecker.i

# target to preprocess a source file
SpellChecker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Unscrambler.dir/build.make CMakeFiles/Unscrambler.dir/SpellChecker.cpp.i
.PHONY : SpellChecker.cpp.i

SpellChecker.s: SpellChecker.cpp.s
.PHONY : SpellChecker.s

# target to generate assembly for a file
SpellChecker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Unscrambler.dir/build.make CMakeFiles/Unscrambler.dir/SpellChecker.cpp.s
.PHONY : SpellChecker.cpp.s

github/progress_bar.o: github/progress_bar.cpp.o
.PHONY : github/progress_bar.o

# target to build an object file
github/progress_bar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Unscrambler.dir/build.make CMakeFiles/Unscrambler.dir/github/progress_bar.cpp.o
.PHONY : github/progress_bar.cpp.o

github/progress_bar.i: github/progress_bar.cpp.i
.PHONY : github/progress_bar.i

# target to preprocess a source file
github/progress_bar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Unscrambler.dir/build.make CMakeFiles/Unscrambler.dir/github/progress_bar.cpp.i
.PHONY : github/progress_bar.cpp.i

github/progress_bar.s: github/progress_bar.cpp.s
.PHONY : github/progress_bar.s

# target to generate assembly for a file
github/progress_bar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Unscrambler.dir/build.make CMakeFiles/Unscrambler.dir/github/progress_bar.cpp.s
.PHONY : github/progress_bar.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Unscrambler"
	@echo "... Combinations.o"
	@echo "... Combinations.i"
	@echo "... Combinations.s"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... Runner.o"
	@echo "... Runner.i"
	@echo "... Runner.s"
	@echo "... SpellChecker.o"
	@echo "... SpellChecker.i"
	@echo "... SpellChecker.s"
	@echo "... github/progress_bar.o"
	@echo "... github/progress_bar.i"
	@echo "... github/progress_bar.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

